### ISSUE TITLE
Redundant downloadings? 

### ISSUE THREAD

**Issue by Jfortin1** [muschellij2/neurocInstall#1]
source("https://neuroconductor.org/neurocLite.R")
Loading required package: neurocInstall
Loading required package: devtools
Using neurocLite version: # neurocInstall package version: 0.4

> neuro_install("neurobase")

Downloading GitHub repo neuroconductor/neurobase@97b36e30657b1bcd75f0dcc591e6bfe9a05ae87f
from URL https://api.github.com/repos/neuroconductor/neurobase/zipball/97b36e30657b1bcd75f0dcc591e6bfe9a05ae87f
Installing neurobase
Downloading GitHub repo neuroconductor/oro.nifti@effca642e07c1b5906d58e7716b73bdd2bdc772a
from URL https://api.github.com/repos/neuroconductor/oro.nifti/zipball/effca642e07c1b5906d58e7716b73bdd2bdc772a
Installing oro.nifti
'/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/1l/3sqk454j5q360xr5byf1_c5w0000gn/T/RtmpXI1Laa/devtools1993508db90a/neuroconductor-oro.nifti-effca64' 
   ‘nifti.Rnw’ 
'/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/1l/3sqk454j5q360xr5byf1_c5w0000gn/T/RtmpXI1Laa/devtools199333bf7549/neuroconductor-neurobase-97b36e3' 
Downloading GitHub repo neuroconductor/oro.nifti@effca642e07c1b5906d58e7716b73bdd2bdc772a
from URL https://api.github.com/repos/neuroconductor/oro.nifti/zipball/effca642e07c1b5906d58e7716b73bdd2bdc772a

Skipping oro.nifti, it is already being installed.
Downloading GitHub repo neuroconductor/neurobase@eb0be1cab626575ca67de4432539a2d25c9bda82
from URL https://api.github.com/repos/neuroconductor/neurobase/zipball/eb0be1cab626575ca67de4432539a2d25c9bda82
Installing neurobase
Downloading GitHub repo neuroconductor/oro.nifti@effca642e07c1b5906d58e7716b73bdd2bdc772a
from URL https://api.github.com/repos/neuroconductor/oro.nifti/zipball/effca642e07c1b5906d58e7716b73bdd2bdc772a
Installing oro.nifti
'/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/1l/3sqk454j5q360xr5byf1_c5w0000gn/T/RtmpXI1Laa/devtools199358092292/neuroconductor-oro.nifti-effca64' 
   ‘nifti.Rnw’ 
'/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/1l/3sqk454j5q360xr5byf1_c5w0000gn/T/RtmpXI1Laa/devtools199369c44729/neuroconductor-neurobase-eb0be1c' 
Installation failed: Command failed:
 '/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/1l/3sqk454j5q360xr5byf1_c5w0000gn/T/RtmpXI1Laa/devtools199369c44729/neuroconductor-neurobase-eb0be1c'  
 * installing to library ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library’
* installing *source* package ‘neurobase’ ...
** R
** preparing package for lazy loading
Error : package ‘oro.nifti’ 0.6.2 was found, but >= 0.7.2 is required by ‘neurobase’
ERROR: lazy loading failed for package ‘neurobase’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/neurobase’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/neurobase’

Downloading GitHub repo neuroconductor/neurobase@78c1b2cff8e42901a8b1111bb6b7208982e8df35
from URL https://api.github.com/repos/neuroconductor/neurobase/zipball/78c1b2cff8e42901a8b1111bb6b7208982e8df35
Installing neurobase
Downloading GitHub repo neuroconductor/oro.nifti@c2875596fdef12c2fcfa3425cabb82a25e7900fa
from URL https://api

.github.com/repos/neuroconductor/oro.nifti/zipball/c2875596fdef12c2fcfa3425cabb82a25e7900fa
Installing oro.nifti
'/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/1l/3sqk454j5q360xr5byf1_c5w0000gn/T/RtmpXI1Laa/devtools19933e424071/neuroconductor-oro.nifti-c287559' 
   ‘nifti.Rnw’ 
'/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/1l/3sqk454j5q360xr5byf1_c5w0000gn/T/RtmpXI1Laa/devtools199375e06768/neuroconductor-neurobase-78c1b2c' 
Downloading GitHub repo neuroconductor/oro.nifti@c2875596fdef12c2fcfa3425cabb82a25e7900fa
from URL https://api.github.com/repos/neuroconductor/oro.nifti/zipball/c2875596fdef12c2fcfa3425cabb82a25e7900fa
Skipping oro.nifti, it is already being installed.

sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.2

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.12.0.9000

loaded via a namespace (and not attached):
 [1] httr_1.2.1           R6_2.2.0             BiocInstaller_1.24.0
 [4] tools_3.3.2          withr_1.0.2          curl_2.3            
 [7] memoise_1.0.0        knitr_1.15.1         callr_1.0.0.9000    
[10] git2r_0.18.0         pkgload_0.0.0.9000   digest_0.6.11       
[13] pkgbuild_0.0.0.9000

**Comment by muschellij2** [comment]
Do you know if this still exists?

**Comment by muschellij2** [comment]
This should be fixed in the releases.
